//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restopay
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersInProgress
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public int Quantity { get; set; }
        public double Amount { get; set; }
        public string Category { get; set; }
        public int TableNumber { get; set; }
        public long OrderNumber { get; set; }
        public string DateTime { get; set; }
        public string CookStatus_ { get; set; }
        public string BartenderStatus_ { get; set; }
        public string WaiterStatus_ { get; set; }
    }
}
