//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestopayStaff
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProductsDatabaseEntities : DbContext
    {
        public ProductsDatabaseEntities()
            : base("name=ProductsDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<appetizer> appetizers { get; set; }
        public virtual DbSet<beverage> beverages { get; set; }
        public virtual DbSet<cart> carts { get; set; }
        public virtual DbSet<dessert> desserts { get; set; }
        public virtual DbSet<mainCourse> mainCourses { get; set; }
        public virtual DbSet<OrdersInProgress> OrdersInProgresses { get; set; }
        public virtual DbSet<ArchivedOrder> ArchivedOrders { get; set; }
    
        public virtual ObjectResult<Nullable<long>> GetNextSequenceValue()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("GetNextSequenceValue");
        }
    }
}
